### ISSUE TITLE
Get lost curse should be aware of minetest_game map mod

### ISSUE THREAD

**Issue by hlqkj** [hlqkj/catcommands#1]
The [`map`](https://github.com/minetest/minetest_game/blob/master/mods/map) mod will restore the minimap for a cursed player, see:

https://github.com/minetest/minetest_game/blob/92701885d086e5123c2c8cca0774e9d9e2327558/mods/map/init.lua#L38-L45

and

https://github.com/minetest/minetest_game/blob/92701885d086e5123c2c8cca0774e9d9e2327558/mods/map/init.lua#L15-L26

The [`map.update_hud_flags`](https://github.com/minetest/minetest_game/blob/92701885d086e5123c2c8cca0774e9d9e2327558/mods/map/init.lua#L15) function should be overridden here and handle stuff accordingly.

**Comment by wsor4035** [comment]
https://github.com/BlockCityCreative/catcommands/commit/1d18ad4d45c303785fcb1454180a3ac6c74406e4 has been completed
