### ISSUE TITLE
Refactor the code to expose an API

### ISSUE THREAD

**Issue by hlqkj** [hlqkj/catcommands#3]
The mod should use a namespace (eg. `catcommands`) with a small set of functions which could be needed by other mods (eg. checking if a player is vanished, etc).

**Comment by wsor4035** [comment]
done in https://github.com/BlockCityCreative/catcommands/commit/c3441829bb9ccd3f3e1edbdfdb952ec26af4270d

**Comment by hlqkj** [comment]
Great work! You could try to send Ezhh a pull request...

**Comment by wsor4035** [comment]
> Great work! You could try to send Ezhh a pull request...

i believe they have left/been inactive in minetest for a long time
